### PR TITLE
Update `minio-go` dependency

### LINKED ISSUE #2: Get rid of second `GetObject()` call inside of `sizeWithoutTrailer()`
Currently, `sizeWithoutTrailer()` internally calls `GetObject()` a second time, because of a `MinIO` bug that prevents us from correctly rewinding the reader offset using `Seek(0, 0)`.

After the [fix PR](https://github.com/minio/minio-go/pull/1649) is merged, we can update the dependency and reuse the S3 object.

### PR DESCRIPTION
**Pull request by ghost**
Closes #2

### CODE REVIEW

**Comment by ramondeklein** [comment]
Not sure why we use the Minio library here instead of the default AWS SDK.

**Comment by florian-sneller** [comment]
> Not sure why we use the Minio library here instead of the default AWS SDK.

This was a suggestion from @frank-sneller when he gave me the task. At the end it doesn't matter which module to use here I think. The AWS SDK is more complicated to use (imho) and might distract from the actual code that we want to showcase in this example project.

**Comment by frank-sneller** [comment]
The AWS SDK is pretty big and large, so the minio library is a bit more lean and mean. But in the end both will accomplish the same thing.

**Comment by flobernd** [comment]
Is it ok to merge this?

**Review by ramondeklein — APPROVED** [review]

**Pull request merged**
